### ISSUE TITLE
Hebrew Metheg not well aligned

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [libertinus-fonts/libertinus#106]
Wikipedia article [Combining Grapheme Joiner](https://en.wikipedia.org/wiki/Combining_Grapheme_Joiner) has the following example for the use of Hebrew Metheg:
- he + metheg + pathah הַֽ
- he + metheg + CGJ + pathah הֽ͏ַ

However both of them does not well aligned when comparing to Ezra SIL.
![snapshot](https://i.imgur.com/HnhvZ7i.png)

**Comment by mgavioli** [comment]
I only have a very rudimentary knowledge of Hebrew and its diacritics are a very dark spot to me.

However, Meteg positioning and in general the combination of Hebrew cantillation and vowel marks seems to me quite a complex matter (see for example https://en.wikipedia.org/wiki/Meteg ), and I am not sure a generalist typeface like Libertinus can be expected to support them beyond the most common mark combinations (i.e. vowels); possibly, for a scholarly Biblical Hebrew usage a specialized typeface, like Ezra SIL, has to be used anyway (maybe for other reasons as well).

But this is just my opinion, of course.

**Comment by khaledhosny** [comment]
I think this should not be too hard to fix; we need `mkmk` anchor between `pathah + metheg` and `metheg + pathah` (i.e. the same anchor, but once for `pathah` as base and `metheg` and once for the reverse), and it should work more or less OK.

**Comment by mgavioli** [comment]
@khaledhosny : well, as I understand the issue, it is not simply a matter of fixing the patah+meteg and the meteg+patah combinations.

The meteg can occur with each of the nine Hebrew vowel marks encoded in Unicode, can have three different positions (before, after or even in between of compounded marks) and, in Unicode, it also takes over the role of some sof pasuq mark with specialised usage from which it is not differentiated.

The wikipedia article I cited above lists seven different ways for encoding sequences of marks including meteg, with the help of both CGJ and ZWJ.

Not for the faint of heart, I daresay...

**Comment by khaledhosny** [comment]
I have zero experience with Hebrew, so whatever solution you and the people who have stack here come up with is fine by me. Leaving this open for some potential future volunteer is also fine by me.

**Comment by KrasnayaPloshchad** [comment]
I have tested several fonts including in Windows 10: Arial, Cambria, Calibri, Segoe UI, Tahoma and Times New Roman. All of them supports Hebrew and they are all passed for such combination. So I think it's valuable to add the same anchors in Libertinus Serif.

**Comment by KrasnayaPloshchad** [comment]
Also see: https://docs.microsoft.com/en-us/typography/script-development/hebrew

**Comment by khaledhosny** [comment]
Someone who knows Hebrew needs to fix this.

**Comment by clsn** [comment]
METEG is the _only_ cantillation that arguably has a life outside of Biblical typesetting.  It's still not particularly common beyond prayer-books and the like, and maybe poetry.  It should appear to the left of the vowel, like most of the other cantillations.  Situations involving METEG on the right of the vowel, or even *inside* the vowel (between the parts of a HATAF-SEGOL, etc, which happens in some MSS of the Bible) are really _really_ of marginal importance unless you're printing a Bible, and probably half the time not even then.  (AFAIK, it isn't actually known whether it even means anything that the METEG is placed differently, or if the scribe just felt like combining the vowel and the METEG in another fashion.)  It should never be placed above or below or atop a vowel like PATAH.  Ideally, yes, it's nice if you can handle all the oddball situations, but if we at least put it on the left all the time it'll satisfy most people most of the time, and fixing the details can be pushed off for a later release.

(And hey, it turns out there are a few places in the Aleppo Codex that appear to have a HATAF-HIRIQ.  Don't go looking for extra trouble.)
