### ISSUE TITLE
Greek lowercase italic is not a real italic

### ISSUE THREAD

**Issue by kiwi0fruit** [libertinus-fonts/libertinus#132]
Lowercase Greek italic (regular, semibold, bold) in Libertinus Serif only slanted instead of real italic: compare italic μ with italic u for example and see that italic μ simply automatically slanted regular μ (actually all greek lowercase italic poorly designed). Because of that it looks worse than Computer Modern or [GFS Porson](https://fontlibrary.org/en/font/gfs-porson). I wish this font to be better that CM so this should be fixed someday.

As a solution:

Adapt GFS Porson (OFL) and MathJax Computer Modern (OFL) - use Porson's "curls". CM Greek lowercase letters look ideal for math (also worth taking regular and italic Υ and Ω from CM). But I think it's better to stick closer to GFS Porson design to have a distinct look from CM (but it's a harder way).

I also suggest to fix: 
* regular μ, ν, γ - adapt from Noto Serif (OFL),
* regular semibold μ - adapt from Noto Serif,
* regular bold μ, ν - adapt from Noto Serif,
* regular ψ - adapt from [Gentum Basic](https://fontlibrary.org/ru/font/gentium)/[Gentum Plus](https://fontlibrary.org/ru/font/gentium-plus) (OFL).

So more info is [here](https://github.com/kiwi0fruit/open-fonts/tree/master/libertinus).

**Comment by khaledhosny** [comment]
I think people unfamiliar with intrinsic details of these fonts (like me) will need some visual comparisons to make any sense of this.

**Comment by kiwi0fruit** [comment]
Hmm. I guess the best way is read for some time [this article](https://en.wikipedia.org/wiki/Oblique_type). Then compare regular and italic sections in:

* [Libertinus Serif](https://fontlibrary.org/en/font/libertinus-serif). It's only oblique. It also seems to be automatically slated - it's even worse.
* [Gentium Plus](https://fontlibrary.org/ru/font/gentium-plus). It's also only oblique. But the glyphs are adaped to slant so they look nice.
* [PFS Porson](https://fontlibrary.org/en/font/gfs-porson). Using it together with Libertinus Serif can be considered to be a real italics because greek lowercase would have changed letterforms not simply oblique.

Latin in Libertinus Serif has italics not simply oblique. But I guess it's not necessary that Libertinus would have italic instead of proper oblique. But at least flawed oblique should be fixed.

**Comment by khaledhosny** [comment]
I know the difference between oblique and italic, I’m asking for a comparison between the Greek glyphs in the fonts you mention.

**Comment by kiwi0fruit** [comment]
Here are screenshots:

gentium-regular-auto-slanted:  
![gentium-auto-slanted](https://user-images.githubusercontent.com/19735117/36630016-bf6fe222-1991-11e8-8b30-efc56e1177ac.png)  
gentium-oblique:  
![gentium-oblique](https://user-images.githubusercontent.com/19735117/36630017-bf97385e-1991-11e8-8682-aff3d9e32346.png)  
libertinus-regular-auto-slanted:  
![libertinus-auto-slanted](https://user-images.githubusercontent.com/19735117/36630018-bfbd670e-1991-11e8-999b-2899a6a2debd.png)  
libertinus-oblique:  
![libertinus-oblique](https://user-images.githubusercontent.com/19735117/36630019-bfdf82b2-1991-11e8-8e5f-0c1bbc1ac502.png)

**Comment by dajare** [comment]
For the banter (and hopefully some help seeing what might be at stake), here are three comparisons: Cambria and Brill both have "true" italics; SBL Greek does not. (Both Brill and SBL Greek were designed by John Hudson, btw.) Also potentially useful: Gerry Leonidas's [Greek type design][g] resources.

[![greek-types-comparison][1]][1]

As noted, the "true" italic lines some character spacing applied to align more closely with the upright versions. This was not done in the SBL Greek "slanted" lines.

[1]: https://user-images.githubusercontent.com/40625/37669488-dbe48aae-2c5e-11e8-9976-1881df3f9c8b.png "Click for full-sized image"
[g]: https://leonidas.net/greek-type-design/

**Comment by kiwi0fruit** [comment]
I'm also curious which characters are preferable by Greek People. For example [this font](https://fontlibrary.org/en/font/asea-textfonts) has specific Greek regular and latin-like italics. I guess such letterforms might be better for Greek people.

Actually there should be two OpenType styles: for Greek texts and for math texts.

**Comment by dajare** [comment]
@kiwi0fruit  - This question came up in [an epic Typophile forum thread][t]. It's actually worth a read through, if you haven't seen it before.

[t]: http://www.typophile.com/node/101331

**Comment by kiwi0fruit** [comment]
@dajare Do you know some contacts in GFS so they can be pointed here and asked if they are interested in helping?

**Comment by kiwi0fruit** [comment]
Nice example of true italics are [Lingua Franca](https://fontlibrary.org/en/font/lingua-franca) / [Linguistics Pro](https://fontlibrary.org/en/font/linguistics-pro).

Linguistics Pro has regular preview. Italic preview can be found in this [math font review](http://math.sut.ac.th/lab/software/texlive/texmf-doc/doc/english/free-math-font-survey/survey.pdf) on Fig.23.

**Comment by mgavioli** [comment]
As the OP suggests a rather deep re-drawing or modification of the current Greek 'italic', I think it worth to attempt to understand what 'true italic' may mean for the a Greek typeface and, possibly, for a Latin typeface too.

Italic as we now know it, was a deliberate invention of the Aldo Manuzio milieu at the end of the XV / beginning of XVI century (I think a precise date can be dug out, but it is not so important). Of course, it was not a creation totally _ex nihilo_, but rather it relied on (some of) the cursive hands in use at the time, with an additional process of stylisation; the whole goal was a typeface allowing a more compact setting of the text (less paper!) without jeopardising legibility (as, for instance, a smaller pitch would have done). Given its origin, the main characteristic of the italic was and still is its cursiveness (for what is worth, here in Italy, where the italic was born, the term for it is still "corsivo"), the slant being a rather automatic consequence of the writing _currenti calamo_.

It is important to remember that it was **not** intended as a stylistic variant of another, upright, typeface but as a typeface in its own; in fact it was not intended to go together with an upright typeface at all, but it was used to set entire books, and so remained for some centuries. The idea that the same typeface may have an upright and an italic variant is, I believe, relatively recent. And IMHO it is a process not yet completed. By comparing the upright and italic shapes of almost any (serif) font, the differences are evident:
- the ductus of many letters is different and requires much less pen lifts to write each letter
- the serif system is completely different
- the distribution of the contrast is often different (in some case more than in other)
- some letter forms are structurally different.

I'll make only two examples, a rather traditional design, like Bitstream American Garamond (sorry for the poor screen shot!) and a quite recent and very eclectic design like Huerta Tipográfica's Alegreya:

![bitstreamamericangaramond](https://user-images.githubusercontent.com/1420743/38377357-0c21a7d0-38fb-11e8-917d-3f967067319b.png)

![alegreya-ht](https://user-images.githubusercontent.com/1420743/38377366-127b38c6-38fb-11e8-8b61-faf46e1359d0.png)

Compare, in the first (Garamond), the contrast distribution of the 'a', the 'e' and the 'z'; the ductus of 'e', 'h', 'm', 'n', 'r', 'u'; the letter forms of 'a' and 'k'.
In the second (Alegreya), the contrast distribution of the 'c', the 'e' and the 'z' and the different solution for most of the stems; the ductus of the same letters as above plus 'b', 'd', 'p', 'q' and 'w'; the letter form of 'a', 'g', 'k'.
The difference in the serif systems is obvious.

Upright and italic are (still?) two different typefaces, in some cases more and in other less, which we 'pack' together more because we are used to this rather than for instrinsic qualities. Of course, this does not exclude that they can nicely go together, but this happens also with 'officially' different typefaces.

These are some thoughts about what "true italic" may mean for the Latin typography. The Greek typographic evolution had nothing of this kind; there was no Manuzio, no italic at all, The Greek italic seems to be a rather recent 'innovation' on the wave of what Hudson, in the Typophile's thread quoted above, calls the 'Romanisation' of the Greek typefaces. In fact, as Hudson again repeats several times, the basis of the most widely used and 'accepted' Greek typefaces lies in the Byzantine hands, quite cursive in comparison to the textual hands used in 'Latin' Europe, in use when Greek typography begun.

The tradition of the Greek typography is inherently cursive; so to speak, it is **already italic** in itself. The only -- or the most obvious -- device left to differentiate another style is the slant. In fact, in practically all the Greek examples quoted above the "italic" is only recognizable for its slant (a few details a part).

Or, paradoxically, the **real** Romanisation could be to keep the current Greek shapes as italic and add an upright style; which has been in fact attempted, usually with poor results. Because the Greek writing system, its tradition and the way it developed letter forms over the centuries is different from their Latin counterparts (for historical reasons, the Greek typography also had less opportunities to flourish and develop).

So, what "true italic" means in the Greek context? Or even: does Greek **need** an italic at all? Just because Latin typefaces have a (as we saw, not always very correlated) italic, also Greek typefaces need one? Why not Arabic typefaces then, or Devanagari, or Korean...

Of course, all the above does not exclude that the current Libertinus Greek "italic" can be improved; but the direction and the goal of this improvement in order to arrive at a more consistent and convincing system remains to my eyes rather obscure.

**Comment by mgavioli** [comment]
Another thought: most of the Greek typefaces we are accustomed to see (and all the examples above) are:
- sans serif
- cursive
- with strong contrast (usually with very high pen angles).

Possibly, something of this kind may be found among the endless array of Latin fonts, but it is definitely not a common occurrence and would almost surely look peculiar. This **systemic** difference has to be kept in mind while transposing ideas and devices form the Latin writing system (of today!) to the Greek writing system.

**Comment by khaledhosny** [comment]
Feel free to send a pull request if you think any action is needed here.
