### ISSUE TITLE
Upper case A, Greek Lambda and Cyrillic glyphs uni0466, uni0467

### ISSUE THREAD

**Issue by StefanPeev** [libertinus-fonts/libertinus#161]
The upper part of the glyphs **Upper case A, Greek Lambda**, **Cyrillic glyphs uni0466, uni0467** and derivatives thereof differs in different styles and languages.

![lsbi-a-01-uc](https://user-images.githubusercontent.com/12949369/38772764-3bc73862-4047-11e8-8042-8618955793d0.png)

![lsbi-lambda-01-uc](https://user-images.githubusercontent.com/12949369/38772766-41f88b82-4047-11e8-97ce-4361bddcd193.png)

![lsbi-uni0466-uni0467-01-uc-lc](https://user-images.githubusercontent.com/12949369/38772768-46e78896-4047-11e8-9ac4-1fc2094b6e67.png)

**Comment by StefanPeev** [comment]
If the Libertinus Serif will be compared with Times New Roman, then all these cases should look the same (whether we speak for Latin, Cyrillic or Greek).

**Comment by khaledhosny** [comment]
Sounds good then, no objection.

**Comment by mgavioli** [comment]
Of course, there is always a measure of personal taste in all these questions, but IMHO:

1) The Serif Regular – Italic relation seems to me totally reasonable; the Bold – Bold Italic much less and, in case, I would make the latter uniform to the former (but the very concept of Bold Italic is largely a typographic nonsense, so...)

2) As far as I know, Greek has a palaeographic and typographic history very different from the Latin writing system and, if one really has to compare to it, much more -- as a whole -- in the "italic" side than in the upright; so, again the current Greek solution seems to me quite reasonable.

3) I have not enough knowledge of Cyrillic to say anything about it, particularly for 'special case' letters like the various _yus_. What a 'native writer/reader' of them would have to say?

4) Times New Roman does not strike me as a particularly reliable paragon of typographic quality. Gentium Plus, Liberation and Noto Serif (the only one to include the _yus_ Cyrillic letters) all have strongly 'Romanized' Greek capitals; in fact, for several of them, they use simple references to the Latin similar glyphs, which is a choice. Libertinus (as Linux Libertine before it) made a different choice, which does not look to me particularly bizarre. But, as I said, it might be subjective.

**Comment by StefanPeev** [comment]
Well, I disagree. We need to look at the history of Linux Libertine (as a primary source for Libertinus project) and not the history of Latin, Cyrillic or Greek scripts. I maintain that the Libertinus project is a chance we to solve properly what was not solved well in Linux Libertine. So let me know which are in your view the primary sources of Linux Libertine. How do you classify the Linux Libertine - as a Garalde type, Transitional type or as a Modern type (Didone like) typeface?
The second question is - don't you think that we need to prepare Libertinus styles for interpolation? If we do it, the Libertinus will be more consistent font family and it could have Regular, Medium, Semibold and Bold styles.

**Comment by KrasnayaPloshchad** [comment]
So what about this?
https://commons.wikimedia.org/wiki/File:Wikipedia-logo-v2-en.svg

**Comment by StefanPeev** [comment]
As far as I know this is a Garalde like apex:

![lsbi-a-01-uc](https://user-images.githubusercontent.com/12949369/38772764-3bc73862-4047-11e8-8042-8618955793d0.png)

You could find it in Garamond - in all styles and for all scripts (including Cyrillic and Greek).

**Comment by mgavioli** [comment]
@StefanPeev : 

1) **Sources**: sources of inspiration for Linux Libertine have never been documented AFAIK; it clearly looked at some Garalde, but which one and what else (because there is clearly something else too), nobody knows except its creator.

2) **Classification**: Me too I see Linux Libertine / Libertinus mostly as a Garalde, with some Transitional tendencies: less flex, serifs more squared rather than triangular, flatter top serifs ('i', 'm', 'n', 'u' and 'A'!) and so on.

3) **Interpolation**:
- IMHO, I do not think we **need** to prepare Libertinus to interpolation. It would probably be nice and I would love to see a Light (ok, this would be extrapolation...), but the preparation would be a very big task as well as the interpolation itself, as I would not blindly trust the outcome of an algorithm, which knows little or nothing about contrast balancing and counter-space management, requiring a review of the result glyph by glyph.
- All the points above, though, does not seem to me to have to do with interpolation: I assume we would interpolate between upright and upright and between italic and italic, as well as between 'A' and 'A' and between 'Lambda' and 'Lambda'; surely not between upright 'A' and italic 'Lambda' or 'little Yus'.
- One notable exception is the Bold Italic case you quote: that apex of the bold italic 'A' is definitely out of system and should be fixed. There might be other too.

**Comment by khaledhosny** [comment]
I think having interpolatable masters would be awesome, and I’d be more than happy to kill one more source of bugs and inconsistencies and drop the separate semi bold weight and interpolate it instead. Any effort towards this is highly appreciated.

But I agree with @mgavioli that the issue here shouldn’t affect interpolatablilty. But I have no opinion here either way.

**Comment by StefanPeev** [comment]
I'll prepare all basic Latin glyphs and basic Cyrillic glyphs for interpolation and I'll upload them as UFO files. Thus anybody will be able to test them and gives his comments. If this experiment proves to be a good one, the glyphs could be used for the whole Libertunus Serif font.

**Comment by khaledhosny** [comment]
I guess we can close this now.
