### ISSUE TITLE
Add SemiBold and SemiBold-Italic weights for Sans

### ISSUE THREAD

**Issue by cssobral2013** [libertinus-fonts/libertinus#200]

**Comment by crti** [comment]
Since I found Linux Biolinum I liked and used it much and now have migrated to Libertinus Sans. Before the addition of SemiBold weights I would very much like a BoldItalic variant added, which would allow to use this wonderful font very broadly. I found https://ctan.org/pkg/libertinus-otf] is providing libertinussans-bolditalic.otf but I do not like this version. 
![libsansboit](https://user-images.githubusercontent.com/1004113/50399370-3997c700-077f-11e9-83b2-d1c45281eb50.png)

**Comment by khaledhosny** [comment]
Any one is free to contribute addition fonts.
