### ISSUE TITLE
Not possible to use Libertinus serif semibold in MS Word and other programs

### ISSUE THREAD

**Issue by EgUG** [libertinus-fonts/libertinus#201]
If Libertinus serif bold and serif semibold are installed, it is not possible to use semibold in MS Word 2016, PowerPoint 2016 and Publisher 2016. PowerPoint and Publisher do no not recognize them, Word makes no differences between bold and semibold (see picture).
![capture_001_18072018_104532](https://user-images.githubusercontent.com/41321085/42870849-34bea6aa-8a79-11e8-8a13-27dff869ec2c.jpg)
In Gimp it is no problem to choose the different fonts.

**Comment by alerque** [comment]
This might be a limitation of Word itself, not of the font. Some programs don't actually try to present what is available to the user, they just look for if there is X or not. In this case Gimp might be scanning the available font variants asking "what weights are there is this family" and displaying everything it finds, while Word might be just asking the system "is there a bold version of this family" and displaying whatever the closest approximation of that is.

Do you have examples of other fonts with more than 2 weights showing up properly in your version of Word?

**Comment by khaledhosny** [comment]
Word and Windows GDI can’t handle more than the 4 badic font styles;
regular, bold, italic, and bold italic. There is however a work around for
this, I’ll check if we do this already or not.

>

**Comment by alerque** [comment]
@EgUG Some font foundries work around these limitations by generating distributing their fonts in different groups with the different weights or styles listed under different font names instead of actually being different weights and styles of the same font. This makes them available to older (or just poorly developed) software, but that comes at the expense of making them obnoxious to use in software that _does_ support OTF features and a full spectrum of weights.

As an open-source project development on this font has mostly concentrated on a clean implementation using Unicode standards and standardized open-type features. This makes them quite pleasant to use in modern software. Even if the upstream project does not opt to provide this particular work around, you should know that you can always build it yourself with alternative names for different styles.

This is something that comes up in the context of not being able to reach the open-type features like ligatures and alternative glyphs in some software. There are tools for generating static font files under new names with whatever more advanced features you want enabled or disabled by default for use in programs that otherwise don't have the chops to access those features.

**Comment by khaledhosny** [comment]
The solution here is to  use name IDs 1 (Font Family) and 2 (Font Subfamily) only for the basic 4 variants, and name IDs 16 (Typographic Family) and 17 (Typographic Subfamily) for unrestricted family names.

This way in legacy applications there will be two families; Libertinus Serif with 4 styles and Libertinus Serif Semibold with 2 styles, and only Libertinus Serif with 6 styles in more modern applications.

**Comment by alerque** [comment]
Wow, that's a hack but clever.

**Comment by khaledhosny** [comment]
I don’t take the credit for it though, it is a common practice and I even believe that the Typographic name IDs were added to the spec specifically to work around Windows legacy API limitation.

**Comment by alerque** [comment]
I'd be willing to bet they were added just for that purpose. I was referring to whoever had to figure out a way to make a spec that let modern programs do sensible things with new features while not entirely blocking access in older ones.
