### ISSUE TITLE
Adjust kerning to some math symbols

### ISSUE THREAD

**Issue by jco2** [libertinus-fonts/libertinus#203]
By looking at the sample math file we can see that kerning between math symbols should be adjusted:
![adjust_kerning_bar](https://user-images.githubusercontent.com/29073309/43002890-b983485c-8c2a-11e8-9a16-a073a0bf5b58.png)
![odd_kerning](https://user-images.githubusercontent.com/29073309/43002891-b9ab48f2-8c2a-11e8-8abb-d7717bbd044d.png)

**Comment by khaledhosny** [comment]
There is really no way around this with Libertinus design. There is no kerning in math mode (in the text kerning sense) except in LuaTeX, and even there you can’t kern an operator with and alphabet symbol AFAIK since these are different math noads (in TeX speak). Adjusting the glyph side bearing (e.g. making the tail of the `j` protrude to the left) will cause issues like #111.

**Comment by jco2** [comment]
However the STIX2 OpenType font improves the kerning in these examples, but it may be because of the design of the font (the italic 'j' is less slanted and the italic 'i' has more space in the sides)?

By the way I'm resizing some math symbols, I was even thinking of using the symbols from STIX2 which are very readable with some tweaks. Is that okay ? Apparently the license is [SIL Open Font License](http://stixfonts.org/user_license.html).

**Comment by khaledhosny** [comment]
I copied some symbols from STIX 2 already, but I’d rather not copy much to change the character of this font.
